### ISSUE TITLE
Blending

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/sinclair#12]
Create new services by blending the outputs of others

```
ServiceOne
  source: someFirstService
  methods:
    methodOne:
      mask: MaskedMethodName
    methodTwo: true
ServiceTwo:
  source: someSecondService
  methods:
    methodOne: true
// Allow blending of just services, or add a third service in the mix
ServiceThree
  source: someThirdService
  methods:
    methodOne:
      blend: ServiceOne.methodOne
    methodTwo:
      blend: ServiceTwo.methodOne
    methodThree: true
```
