### ISSUE TITLE
Carbon Integration

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/sinclair#14]
Allow sinclair to manage the transition of objects between services by using carbon events

```
ServiceName
  source: fileName
  methods:
    methodOne:
       carbon:
          returnValue: someCarbonClass.someCarbonEvent
```
