### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/sinclair#9]
Sinclair should be able to say what methods are required for an export. This should be able to use the feature flags, and be reference based. This probably needs to create a tree, and check for cyclical dependencies
For example, 

```
Interface-One: 
  methods: 
   - method1
   - method2
   - method3
Interface-Two:
  extends: Interface-One
  methods:
   - method4
```
